name: Run unit tests

on: push

jobs:
  test:
    runs-on: ubuntu
    steps:
      - name: ğŸ“ Check out code
        uses: actions/checkout@v4

      - name: ğŸ§ª Run tests
        run: "npm run dev"
    

